import type { NodeKind, WorkflowEdge, WorkflowNode, WorkflowState } from "./model";

const node = (
  id: string,
  type: NodeKind,
  label: string,
  x: number,
  y: number,
  properties: WorkflowNode["properties"] = {},
): WorkflowNode => ({ id, type, label, position: { x, y }, properties });

const edge = (
  id: string,
  source: string,
  sourcePort: string,
  target: string,
  label?: string,
): WorkflowEdge => ({ id, source, sourcePort, target, targetPort: "input", label });

export const createSeedWorkflow = (): WorkflowState => ({
  revision: 0,
  nodes: [
    node("patient-arrives", "node", "Patient arrives", 0, 460, { phase: "Arrival" }),
    node("arrival-type", "condition", "Scheduled arrival?", 220, 460, { phase: "Arrival" }),
    node("scheduled-check-in", "action", "Scheduled check-in & pre-registration", 460, 280, { owner: "Patient access", phase: "Arrival" }),
    node("emergency-triage", "action", "Emergency screening & human triage", 460, 650, { owner: "Triage nurse", phase: "Arrival", review: "Human" }),
    node("critical-at-arrival", "condition", "Critical at arrival?", 720, 650, { phase: "Triage" }),
    node("resuscitate", "action", "Resuscitate & stabilize", 960, 820, { owner: "Emergency response team", phase: "Triage", review: "Human" }),
    node("stabilized", "condition", "Stable for continued care?", 1210, 820, { phase: "Triage" }),
    node("critical-outcome", "node", "Critical care transfer or end-of-life documentation", 1470, 1010, { phase: "Outcome" }),
    node("registration", "action", "Registration, identity & coverage verification", 1470, 430, { owner: "Patient access", phase: "Intake" }),
    node("consent", "condition", "Consent to evaluate and treat?", 1730, 430, { phase: "Intake", review: "Human" }),
    node("informed-refusal", "action", "Document informed refusal & offer safe alternatives", 1990, 160, { owner: "Clinician", phase: "Intake", review: "Human" }),
    node("refusal-outcome", "node", "Refusal recorded; safety plan and outreach arranged", 2250, 70, { phase: "Outcome" }),
    node("clinical-assessment", "action", "Clinical assessment & history", 1990, 500, { owner: "Care team", phase: "Assessment", review: "Human" }),
    node("left-early", "condition", "Patient leaves before care is complete?", 2250, 500, { phase: "Assessment" }),
    node("early-exit", "action", "Document LWBS/AMA, give safety advice & outreach", 2510, 260, { owner: "Care team", phase: "Exception", review: "Human" }),
    node("diagnostics-needed", "condition", "Diagnostic testing needed?", 2510, 580, { phase: "Diagnostics", review: "Human" }),
    node("diagnostic-testing", "action", "Perform diagnostic testing", 2770, 720, { phase: "Diagnostics" }),
    node("abnormal-results", "condition", "Abnormal or critical results?", 3030, 720, { phase: "Diagnostics" }),
    node("abnormal-review", "action", "Clinician reviews and escalates abnormal results", 3290, 600, { owner: "Responsible clinician", phase: "Diagnostics", review: "Human" }),
    node("routine-review", "action", "Clinician reviews routine results", 3290, 850, { owner: "Responsible clinician", phase: "Diagnostics", review: "Human" }),
    node("treatment-plan", "action", "Human-reviewed treatment plan", 3550, 500, { owner: "Clinical team", phase: "Treatment", review: "Human" }),
    node("treatment-accepted", "condition", "Patient accepts treatment plan?", 3810, 500, { phase: "Treatment" }),
    node("declined-treatment", "action", "Document declined treatment & harm-reduction plan", 4070, 250, { owner: "Clinician", phase: "Treatment", review: "Human" }),
    node("procedure-needed", "condition", "Surgery or procedure appropriate?", 4070, 610, { phase: "Treatment", review: "Human" }),
    node("procedure-safety", "action", "Procedure consent & safety review", 4330, 740, { owner: "Procedural team", phase: "Treatment", review: "Human" }),
    node("procedure", "action", "Surgery or procedure", 4590, 740, { owner: "Procedural team", phase: "Treatment" }),
    node("medical-treatment", "action", "Deliver non-procedural treatment", 4590, 480, { owner: "Care team", phase: "Treatment" }),
    node("deterioration", "condition", "Critical deterioration or complication?", 4850, 600, { phase: "Treatment" }),
    node("rapid-response", "action", "Rapid response, stabilize & human reassessment", 5110, 820, { owner: "Rapid response team", phase: "Escalation", review: "Human" }),
    node("inpatient-needed", "condition", "Inpatient admission needed?", 5370, 600, { phase: "Disposition", review: "Human" }),
    node("bed-available", "condition", "Appropriate bed available?", 5630, 760, { phase: "Disposition" }),
    node("bed-escalation", "action", "Bed management escalation & safe holding care", 5890, 930, { owner: "Bed manager", phase: "Disposition", review: "Human" }),
    node("placement-found", "condition", "Internal placement secured?", 6150, 930, { phase: "Disposition" }),
    node("external-transfer", "action", "External transfer with clinical handoff", 6410, 1090, { owner: "Transfer center", phase: "Outcome", review: "Human" }),
    node("transfer-outcome", "node", "Receiving facility accepts care", 6670, 1090, { phase: "Outcome" }),
    node("admit-level", "condition", "Higher-acuity level required?", 6410, 760, { phase: "Inpatient", review: "Human" }),
    node("critical-care", "action", "Admit to critical care", 6670, 650, { owner: "Critical care team", phase: "Inpatient" }),
    node("ward-care", "action", "Admit to ward care", 6670, 860, { owner: "Inpatient team", phase: "Inpatient" }),
    node("transfer-review", "condition", "Transfer between levels of care needed?", 6930, 760, { phase: "Inpatient", review: "Human" }),
    node("level-transfer", "action", "Human-reviewed level-of-care transfer", 7190, 900, { owner: "Inpatient team", phase: "Inpatient", review: "Human" }),
    node("discharge-review", "action", "Human discharge-readiness review", 7450, 600, { owner: "Multidisciplinary team", phase: "Discharge", review: "Human" }),
    node("ready-for-discharge", "condition", "Ready for safe discharge?", 7710, 600, { phase: "Discharge", review: "Human" }),
    node("resolve-barriers", "action", "Resolve delayed-discharge barriers & re-review", 7970, 820, { owner: "Case management", phase: "Discharge", review: "Human" }),
    node("med-reconciliation", "action", "Medication reconciliation & teach-back", 8230, 560, { owner: "Clinician or pharmacist", phase: "Discharge", review: "Human" }),
    node("readmission-risk", "condition", "High readmission risk?", 8490, 560, { phase: "Follow-up", review: "Human" }),
    node("enhanced-transition", "action", "Case review, early follow-up & home supports", 8750, 720, { owner: "Care coordinator", phase: "Follow-up", review: "Human" }),
    node("standard-follow-up", "action", "Schedule standard follow-up", 8750, 430, { owner: "Scheduling", phase: "Follow-up" }),
    node("follow-up-attended", "condition", "Follow-up completed?", 9010, 560, { phase: "Follow-up" }),
    node("follow-up-complete", "node", "Care transitioned; plan updated at follow-up", 9270, 430, { phase: "Outcome" }),
    node("missed-follow-up", "action", "Outreach, safety check & risk escalation", 9270, 720, { owner: "Care coordinator", phase: "Follow-up", review: "Human" }),
    node("outreach-outcome", "node", "Patient re-engaged or contact attempts documented", 9530, 720, { phase: "Outcome" }),
  ],
  edges: [
    edge("edge-arrival-type", "patient-arrives", "next", "arrival-type"),
    edge("edge-arrival-scheduled", "arrival-type", "yes", "scheduled-check-in", "Scheduled"),
    edge("edge-arrival-emergency", "arrival-type", "no", "emergency-triage", "Emergency"),
    edge("edge-scheduled-registration", "scheduled-check-in", "success", "registration"),
    edge("edge-triage-critical", "emergency-triage", "success", "critical-at-arrival"),
    edge("edge-critical-resuscitate", "critical-at-arrival", "yes", "resuscitate", "Critical"),
    edge("edge-critical-registration", "critical-at-arrival", "no", "registration", "Not critical"),
    edge("edge-resuscitate-stable", "resuscitate", "success", "stabilized"),
    edge("edge-stable-registration", "stabilized", "yes", "registration", "Stabilized"),
    edge("edge-stable-outcome", "stabilized", "no", "critical-outcome", "Unable to stabilize"),
    edge("edge-registration-consent", "registration", "success", "consent"),
    edge("edge-consent-assessment", "consent", "yes", "clinical-assessment", "Consents"),
    edge("edge-consent-refusal", "consent", "no", "informed-refusal", "Declines"),
    edge("edge-refusal-outcome", "informed-refusal", "success", "refusal-outcome"),
    edge("edge-assessment-left", "clinical-assessment", "success", "left-early"),
    edge("edge-left-exit", "left-early", "yes", "early-exit", "Leaves early"),
    edge("edge-left-diagnostics", "left-early", "no", "diagnostics-needed", "Continues care"),
    edge("edge-diagnostics-tests", "diagnostics-needed", "yes", "diagnostic-testing", "Testing needed"),
    edge("edge-diagnostics-plan", "diagnostics-needed", "no", "treatment-plan", "No testing"),
    edge("edge-tests-results", "diagnostic-testing", "success", "abnormal-results"),
    edge("edge-results-abnormal", "abnormal-results", "yes", "abnormal-review", "Abnormal / critical"),
    edge("edge-results-routine", "abnormal-results", "no", "routine-review", "Expected"),
    edge("edge-abnormal-plan", "abnormal-review", "success", "treatment-plan"),
    edge("edge-routine-plan", "routine-review", "success", "treatment-plan"),
    edge("edge-plan-accepted", "treatment-plan", "success", "treatment-accepted"),
    edge("edge-treatment-declined", "treatment-accepted", "no", "declined-treatment", "Declines"),
    edge("edge-declined-refusal", "declined-treatment", "success", "refusal-outcome"),
    edge("edge-treatment-procedure", "treatment-accepted", "yes", "procedure-needed", "Accepts"),
    edge("edge-procedure-safety", "procedure-needed", "yes", "procedure-safety", "Procedure"),
    edge("edge-procedure-medical", "procedure-needed", "no", "medical-treatment", "Non-procedural"),
    edge("edge-safety-procedure", "procedure-safety", "success", "procedure"),
    edge("edge-procedure-deterioration", "procedure", "success", "deterioration"),
    edge("edge-medical-deterioration", "medical-treatment", "success", "deterioration"),
    edge("edge-deterioration-response", "deterioration", "yes", "rapid-response", "Deteriorates"),
    edge("edge-deterioration-disposition", "deterioration", "no", "inpatient-needed", "Stable"),
    edge("edge-response-admit", "rapid-response", "success", "inpatient-needed"),
    edge("edge-admission-bed", "inpatient-needed", "yes", "bed-available", "Admit"),
    edge("edge-admission-discharge", "inpatient-needed", "no", "discharge-review", "Outpatient care"),
    edge("edge-bed-admit", "bed-available", "yes", "admit-level", "Bed ready"),
    edge("edge-bed-escalation", "bed-available", "no", "bed-escalation", "No bed"),
    edge("edge-escalation-placement", "bed-escalation", "success", "placement-found"),
    edge("edge-placement-admit", "placement-found", "yes", "admit-level", "Placed internally"),
    edge("edge-placement-transfer", "placement-found", "no", "external-transfer", "Transfer required"),
    edge("edge-external-outcome", "external-transfer", "success", "transfer-outcome"),
    edge("edge-level-critical", "admit-level", "yes", "critical-care", "ICU / high acuity"),
    edge("edge-level-ward", "admit-level", "no", "ward-care", "Ward"),
    edge("edge-critical-transfer-review", "critical-care", "success", "transfer-review"),
    edge("edge-ward-transfer-review", "ward-care", "success", "transfer-review"),
    edge("edge-transfer-level", "transfer-review", "yes", "level-transfer", "Transfer level"),
    edge("edge-transfer-discharge", "transfer-review", "no", "discharge-review", "Remain at level"),
    edge("edge-level-discharge", "level-transfer", "success", "discharge-review"),
    edge("edge-discharge-ready", "discharge-review", "success", "ready-for-discharge"),
    edge("edge-ready-meds", "ready-for-discharge", "yes", "med-reconciliation", "Ready"),
    edge("edge-ready-barriers", "ready-for-discharge", "no", "resolve-barriers", "Delayed"),
    edge("edge-barriers-meds", "resolve-barriers", "success", "med-reconciliation", "Barriers resolved"),
    edge("edge-meds-risk", "med-reconciliation", "success", "readmission-risk"),
    edge("edge-risk-enhanced", "readmission-risk", "yes", "enhanced-transition", "High risk"),
    edge("edge-risk-standard", "readmission-risk", "no", "standard-follow-up", "Standard risk"),
    edge("edge-enhanced-follow-up", "enhanced-transition", "success", "follow-up-attended"),
    edge("edge-standard-follow-up", "standard-follow-up", "success", "follow-up-attended"),
    edge("edge-early-exit-follow-up", "early-exit", "success", "follow-up-attended", "Outreach follow-up"),
    edge("edge-follow-up-complete", "follow-up-attended", "yes", "follow-up-complete", "Completed"),
    edge("edge-follow-up-missed", "follow-up-attended", "no", "missed-follow-up", "Missed"),
    edge("edge-missed-outcome", "missed-follow-up", "success", "outreach-outcome"),
  ],
});
